### ISSUE TITLE
Merge Argus Design Demo

### ISSUE THREAD

**Issue by mpalmsten** [Coastal-Imaging-Research-Network/Support-Routines#3]
@RobHolman the Argus Design Demo looks good. Can you please issue a pull request (assign me as a reviewer), and we can merge your branch into the master.

**Comment by RobHolman** [comment]
I have requested your pull.  And I am slowly learning about github.

Rob Holman
SECNAV/CNO Chair in Oceanography

104 Ocean Admin Bldg.
CEOAS-OSU
Corvallis, Oregon, USA 97331-5503
ph: 1-541-737-2914
holman@coas.oregonstate.edu
http://cil-www.coas.oregonstate.edu

**Comment by mpalmsten** [comment]
@RobHolman, thanks for doing the pull request!
